echo:
  value: hallo
  test: xxx
  num: 5

test:
  hostprovider: gardener
  baseClusterCloudprovider: gcp

  gardensetup:
    revision:
      prHead: true

  gardener:
    version:
      path: GARDENER_VERSION

  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.14.4
      - version: 1.13.10
