echo:
  value: hallo
  test: xxx
  num: 5

test:
  tests:
  - subCommand: dummy
    testrunPath: testruns/simple.yaml

test-gardener:
  hostprovider: gardener
  baseClusterCloudprovider: gcp

  gardensetup:
    revision:
      prHead: true

  gardener:
    version:
      path: GARDENER_VERSION

  gardener-extensions:
    path: dep-versions.yaml
    structuredJSONPATH: "versions.gardener.extensions"

  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.14.4
  - provider: aws
    kubernetes:
      versions:
      - version: 1.14.4
